# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#179299" }

# Hovered
hovered         = { fg = "#eff1f5", bg = "#1e66f5" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#df8e1d", italic = true }
find_position = { fg = "#ea76cb", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#40a02b", bg = "#40a02b" }
marker_copied   = { fg = "#df8e1d", bg = "#df8e1d" }
marker_cut      = { fg = "#d20f39", bg = "#d20f39" }

# Tab
tab_active   = { fg = "#eff1f5", bg = "#1e66f5" }
tab_inactive = { fg = "#4c4f69", bg = "#bcc0cc" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#8c8fa1" }

# Highlighting
syntect_theme = "~/.config/bat/themes/Catppuccin-latte.tmTheme"

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#bcc0cc", bg = "#bcc0cc" }

# Mode
mode_normal = { fg = "#eff1f5", bg = "#1e66f5", bold = true }
mode_select = { fg = "#eff1f5", bg = "#40a02b", bold = true }
mode_unset  = { fg = "#eff1f5", bg = "#dd7878", bold = true }

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#1e66f5", bg = "#bcc0cc" }
progress_error  = { fg = "#d20f39", bg = "#bcc0cc" }

# Permissions
permissions_t = { fg = "#1e66f5" }
permissions_r = { fg = "#df8e1d" }
permissions_w = { fg = "#d20f39" }
permissions_x = { fg = "#40a02b" }
permissions_s = { fg = "#8c8fa1" }

# : }}}


# : Input {{{

[input]
border   = { fg = "#1e66f5" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border   = { fg = "#1e66f5" }
active   = { fg = "#ea76cb" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#1e66f5" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#ccd0da" }
cand            = { fg = "#179299" }
rest            = { fg = "#7c7f93" }
desc            = { fg = "#ea76cb" }
separator       = "  "
separator_style = { fg = "#acb0be" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#ea76cb" }
exec    = { fg = "#179299" }
desc    = { fg = "#7c7f93" }
hovered = { bg = "#acb0be", bold = true }
footer  = { fg = "#bcc0cc", bg = "#4c4f69" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#179299" },

	# Videos
	{ mime = "video/*", fg = "#df8e1d" },
	{ mime = "audio/*", fg = "#df8e1d" },

	# Archives
	{ mime = "application/zip",             fg = "#ea76cb" },
	{ mime = "application/gzip",            fg = "#ea76cb" },
	{ mime = "application/x-tar",           fg = "#ea76cb" },
	{ mime = "application/x-bzip",          fg = "#ea76cb" },
	{ mime = "application/x-bzip2",         fg = "#ea76cb" },
	{ mime = "application/x-7z-compressed", fg = "#ea76cb" },
	{ mime = "application/x-rar",           fg = "#ea76cb" },

	# Fallback
	{ name = "*", fg = "#4c4f69" },
	{ name = "*/", fg = "#1e66f5" }
]

# : }}}


[icon]

rules = [
    { name = "Desktop/"     ,text = "" },
    { name = "Documents/"   ,text = "" },
    { name = "Downloads/"   ,text = "" },
    { name = "Pictures/"    ,text = "" },
    { name = "Music/"       ,text = "" },
    { name = "Movies/"      ,text = "" },
    { name = "Videos/"      ,text = "" },
    { name = "Public/"      ,text = "" },
    { name = "Library/"     ,text = "" },
    { name = "Development/" ,text = "" },
    { name = ".config/"     ,text = "" },

# Git
    { name = ".git/"          ,text = "", fg = "#F14C28" },
    { name = ".gitignore"     ,text = "", fg = "#41535b" },
    { name = ".gitmodules"    ,text = "", fg = "#41535b" },
    { name = ".gitattributes" ,text = "", fg = "#41535b" },

# Dotfiles
    { name = ".DS_Store"    ,text = "", fg = "#6d8086"},
    { name = ".bashrc"      ,text = "", fg = "#6d8086"},
    { name = ".bashprofile" ,text = "", fg = "#6d8086"},
    { name = ".zshrc"       ,text = "", fg = "#6d8086"},
    { name = ".zshenv"      ,text = "", fg = "#6d8086"},
    { name = ".zprofile"    ,text = "", fg = "#6d8086"},
    { name = ".vimrc"       ,text = "", fg = "#019833" },
    { name = "*.ps1"        ,text = "󰨊", fg = "#4273ca" },

# Text
    { name = "*.txt"   ,text = "", fg = "#89e051" },
    { name = "*.md"    ,text = "", fg = "#ffffff" },
    { name = "*.tex"   ,text = "ﭨ", fg = "#3D6117" },
    { name = "*.org"   ,text = "", fg = "#5dbd7e" },
    { name = "*.norg"  ,text = "", fg = "#5dbd7e" },
    { name = "*.rst"   ,text = "", fg = "#7e60c0" },
    { name = "COPYING" ,text = "", fg = "#cbcb41" },
    { name = "LICENSE" ,text = "", fg = "#cbcb41" },

# Archives
    { name = "*.zip" ,text = "", fg = "#f4b8e4" },
    { name = "*.rar" ,text = "", fg = "#f4b8e4" },
    { name = "*.tar" ,text = "", fg = "#f4b8e4" },
    { name = "*.gz"  ,text = "", fg = "#f4b8e4" },
    { name = "*.7z"  ,text = "", fg = "#f4b8e4" },
    { name = "*.bz2" ,text = "", fg = "#f4b8e4" },
    { name = "*.xz"  ,text = "", fg = "#f4b8e4" },

# Documents
    { name = "*.pdf"  ,text = "", fg = "#b30b00" },
    { name = "*.doc"  ,text = "", fg = "#185abd" },
    { name = "*.doct" ,text = "", fg = "#185abd" },
    { name = "*.docx" ,text = "", fg = "#185abd" },
    { name = "*.dot"  ,text = "", fg = "#185abd" },
    { name = "*.pom"  ,text = "", fg = "#cb4a32" },
    { name = "*.pot"  ,text = "", fg = "#cb4a32" },
    { name = "*.ppm"  ,text = "", fg = "#cb4a32" },
    { name = "*.pps"  ,text = "", fg = "#cb4a32" },
    { name = "*.ppt"  ,text = "", fg = "#cb4a32" },
    { name = "*.potx" ,text = "", fg = "#cb4a32" },
    { name = "*.ppmx" ,text = "", fg = "#cb4a32" },
    { name = "*.ppsx" ,text = "", fg = "#cb4a32" },
    { name = "*.pptx" ,text = "", fg = "#cb4a32" },
    { name = "*.xlc"  ,text = "", fg = "#207245" },
    { name = "*.xlm"  ,text = "", fg = "#207245" },
    { name = "*.xls"  ,text = "", fg = "#207245" },
    { name = "*.xlt"  ,text = "", fg = "#207245" },
    { name = "*.xlsm" ,text = "", fg = "#207245" },
    { name = "*.xlsx" ,text = "", fg = "#207245" },
    { name = "*.csv"  ,text = "", fg = "#207245" },
    { name = "*.ods"  ,text = "", fg = "#207245" },
    { name = "*.ots"  ,text = "", fg = "#207245" },

# Audio
    { name = "*.mp3"  ,text = "", fg = "#d39ede" },
    { name = "*.flac" ,text = "", fg = "#d39ede" },
    { name = "*.wav"  ,text = "", fg = "#d39ede" },
    { name = "*.aac"  ,text = "", fg = "#d39ede" },
    { name = "*.ogg"  ,text = "", fg = "#d39ede" },
    { name = "*.m4a"  ,text = "", fg = "#d39ede" },
    { name = "*.mp2"  ,text = "", fg = "#d39ede" },

# Movies
    { name = "*.mp4"  ,text = "", fg = "#9ea3de" },
    { name = "*.mkv"  ,text = "", fg = "#9ea3de"  },
    { name = "*.avi"  ,text = "", fg = "#9ea3de"  },
    { name = "*.mov"  ,text = "", fg = "#9ea3de" },
    { name = "*.webm" ,text = "", fg = "#9ea3de"  },

# Images
    { name = "*.jpg"  ,text = "", fg = "#3AFFDB" },
    { name = "*.jpeg" ,text = "", fg = "#3AFFDB" },
    { name = "*.tif"  ,text = "", fg = "#3AFFDB" },
    { name = "*.png"  ,text = "", fg = "#3AFFDB" },
    { name = "*.gif"  ,text = "", fg = "#3AFFDB" },
    { name = "*.webp" ,text = "", fg = "#3AFFDB" },
    { name = "*.avif" ,text = "", fg = "#3AFFDB" },
    { name = "*.bmp"  ,text = "", fg = "#3AFFDB" },
    { name = "*.ico"  ,text = "", fg = "#3AFFDB" },
    { name = "*.svg"  ,text = "", fg = "#3AFFDB" },
    { name = "*.xcf"  ,text = "", fg = "#3AFFDB" },
    { name = "*.HEIC" ,text = "", fg = "#3AFFDB" },

# Programming
    { name = "*.c"           ,text = "", fg = "#519aba" },
    { name = "*.cpp"         ,text = "", fg = "#519aba" },
    { name = "*.h"           ,text = "", fg = "#a074c4" },
    { name = "*.hpp"         ,text = "", fg = "#a074c4" },
    { name = "*.rs"          ,text = "", fg = "#dea584" },
    { name = "*.go"          ,text = "", fg = "#7FD6E9" },
    { name = "*.py"          ,text = "", fg = "#FFBC03" },
    { name = "*.pyc"         ,text = "", fg = "#ffe291" },
    { name = "*.pyd"         ,text = "", fg = "#ffe291" },
    { name = "*.pyi"         ,text = "", fg = "#ffbc03" },
    { name = "*.pyo"         ,text = "", fg = "#ffe291" },
    { name = "*.pyx"         ,text = "", fg = "#5aa7e4" },
    { name = "*.js"          ,text = "", fg = "#cbcb41" },
    { name = "*.ts"          ,text = "", fg = "#519aba" },
    { name = "*.tsx"         ,text = "", fg = "#519aba" },
    { name = "*.jsx"         ,text = "", fg = "#519aba" },
    { name = "*.rb"          ,text = "", fg = "#701516" },
    { name = "*.php"         ,text = "", fg = "#a074c4" },
    { name = "*.java"        ,text = "", fg = "#cc3e44" },
    { name = "*.sh"          ,text = "", fg = "#4d5a5e" },
    { name = "*.fish"        ,text = "", fg = "#4d5a5e" },
    { name = "*.swift"       ,text = "", fg = "#e37933" },
    { name = "*.vim"         ,text = "", fg = "#019833" },
	{ name = "*.lua"         ,text = "", fg = "#51a0cf" },
    { name = "*.html"        ,text = "", fg = "#e34c26" },
    { name = "*.css"         ,text = "", fg = "#61afef" },
    { name = "*.scss"        ,text = "", fg = "#f55385" },
    { name = "*.json"        ,text = "", fg = "#cbcb41" },
    { name = "*.toml"        ,text = "", fg = "#6d8086" },
    { name = "*.yml"         ,text = "", fg = "#6d8086" },
    { name = "*.yaml"        ,text = "", fg = "#6d8086" },
    { name = "*.ini"         ,text = "", fg = "#6d8086" },
    { name = "*.conf"        ,text = "", fg = "#6d8086" },
    { name = "*.lock"        ,text = "", fg = "#f80000" },
    { name = "*.nix"         ,text = "", fg = "#7ebae4" },
    { name = "*.m"           ,text = "", fg = "#c04c0b" },
    { name = "*.for"         ,text = "󱈚", fg = "#734f96" },
    { name = "*.lnk"         ,text = "", fg = "#e3459f" },
    { name = "*.opju"        ,text = "", fg = "#f66d54" },
    { name = "Containerfile" ,text = "󰡨", fg = "#384d54" },
    { name = "Dockerfile"    ,text = "󰡨", fg = "#384d54" },

# Misc
    { name = "*.bin" ,text = "", fg = "#05a6f0" },
    { name = "*.exe" ,text = "", fg = "#9F0500" },
    { name = "*.pkg" ,text = "", fg = "#10bb10" },
    { name = "*.bat" ,text = "", fg = "#C1F12E" },

# Default
    { name = "*"  ,text = "", fg = "#abb2bf" }, # files icon
    { name = "*/" ,text = "", fg = "#9f86c4" }, # directories icon
]
