# vim:fileencoding=utf-8:foldmethod=marker
# catppuccin-Latte

# : Flavor {{{

[flavor]
use = ""

# : }}}

# : Manager {{{

[manager]
cwd = { fg = "#b00000" }  # 左上角路径颜色 (Latte)

# Hovered 选项条颜色
hovered         = { fg = "#2e3436", bg = "#8caaee", bold = true }  # Latte


preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#b00000", bold = true, italic = true, underline = true }
find_position = { fg = "#ae6485", bg = "reset", bold = true, italic = true }

# Marker
marker_selected = { fg = "lightgreen",  bg = "lightgreen" }
marker_copied   = { fg = "#df8e1d", bg = "#df8e1d" }
marker_cut      = { fg = "lightred",    bg = "lightred" }
marker_marked   = { fg = "#89a0c3",     bg = "#89a0c3" }

# Tab
tab_active   = { fg = "#2e3436", bg = "#ae6485" }
tab_inactive = { fg = "#abb2bf", bg = "darkgray" }
tab_width    = 1

# Count
count_selected = { fg = "black", bg = "lightgreen" }
count_copied   = { fg = "black", bg = "#df8e1d" }
count_cut      = { fg = "black", bg = "lightred" }

# Border
# border_symbol = " "
border_symbol = "│"
border_style  = { fg = "#3b3e4d" }

# Highlighting
syntect_theme = "C:/Users/ThinkPad/AppData/Roaming/yazi/config/bat-themes/Catppuccin Latte.tmTheme"

# : }}}

# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "darkgray", bg = "#7287fd" }  # Latte

# Mode
mode_normal = { fg = "#89a0c3", bg = "#eff1f5", bold = true }  # Latte
mode_select = { fg = "lightgreen", bg = "#eff1f5", bold = true }  # Latte
mode_unset  = { fg = "lightmagenta", bg = "#eff1f5", bold = true }  # Latte

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#eeeeee", bg = "#7287fd" }  # Latte
progress_error  = { fg = "red", bg = "#7287fd" }  # Latte

# Permissions
permissions_t = { fg = "lightgreen" }
permissions_r = { fg = "lightyellow" }
permissions_w = { fg = "lightred" }
permissions_x = { fg = "lightcyan" }
permissions_s = { fg = "darkgray" }

# : }}}

# : Select {{{

[select]
border   = { fg = "#ae6485" }
active   = { fg = "magenta", bold = true }
inactive = {}

# : }}}

# : Input {{{

[input]
border   = { fg = "#ae6485" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}

# : Completion {{{

[completion]
border   = { fg = "#ae6485" }
active   = { bg = "darkgray" }
inactive = {}

# Icons
icon_file    = ""  #   
icon_folder  = ""  #  
icon_command = ""

# : }}}

# : Tasks {{{

[tasks]
border  = { fg = "#ae6485" }
title   = {}
hovered = { underline = true }

# : }}}

# : Which {{{

[which]
cols = 2
mask            = { bg = "#d3d3d3" }  # Latte
cand            = { fg = "#6c71c4" }  # Latte
rest            = { fg = "darkgray" }
desc            = { fg = "#ae6485" }
separator       = "  "
separator_style = { fg = "darkgray" }

# : }}}

# : Help {{{

[help]
on      = { fg = "magenta" }
exec    = { fg = "cyan" }
desc    = { fg = "gray" }
hovered = { bg = "darkgray", bold = true }
footer  = { fg = "#2e3436", bg = "#abb2bf" }

# : }}}

# : Notify {{{

[notify]
title_info  = { fg = "green" }
title_warn  = { fg = "yellow" }
title_error = { fg = "red" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}

# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "cyan", bold = true },

	# Videos
	{ mime = "video/*", fg = "#9ea3de", bold = true },
	{ mime = "audio/*", fg = "#9ea3de", bold = true },

	# Archives
	{ mime = "application/zip",             fg = "#f4b8e4", bold = true },
	{ mime = "application/gzip",            fg = "#f4b8e4", bold = true },
	{ mime = "application/x-tar",           fg = "#f4b8e4", bold = true },
	{ mime = "application/x-bzip",          fg = "#f4b8e4", bold = true },
	{ mime = "application/x-bzip2",         fg = "#f4b8e4", bold = true },
	{ mime = "application/x-7z-compressed", fg = "#f4b8e4", bold = true },
	{ mime = "application/x-rar",           fg = "#f4b8e4", bold = true },
	{ mime = "application/xz",              fg = "#f4b8e4", bold = true },

	# Documents
	# { mime = "application/doc",   fg = "green" },
	# { mime = "application/pdf",   fg = "green" },
	# { mime = "application/rtf",   fg = "green" },
	# { mime = "application/vnd.*", fg = "green" },

	# Fallback 文件和文件夹字体颜色
	{ name = "*",  fg = "#4c4f69", bold = true }, # files font (Latte)

	{ name = "*/", fg = "#6c71c4", bold = true }, # directories font
	# { name = "*/", fg = "#9f86c4" }, # directories font
	# { name = "*/", fg = "#bd93f9" }, # directories font
	# { name = "*/", fg = "#83a598" }, # directories font
	# { name = "*/", fg = "#80aefa" }, # directories font
	# { name = "*/", fg = "#ae5180" }, # directories font
]

[icon]

rules = [
    { name = "Desktop/"     ,text = "" },
    { name = "Documents/"   ,text = "" },
    { name = "Downloads/"   ,text = "" },
    { name = "Pictures/"    ,text = "" },
    { name = "Music/"       ,text = "" },
    { name = "Movies/"      ,text = "" },
    { name = "Videos/"      ,text = "" },
    { name = "Public/"      ,text = "" },
    { name = "Library/"     ,text = "" },
    { name = "Development/" ,text = "" },
    { name = ".config/"     ,text = "" },

# Git
    { name = ".git/"          ,text = "", fg = "#ff8800" },  # 
    { name = ".gitignore"     ,text = "", fg = "#ff8800" },
    { name = ".gitmodules"    ,text = "", fg = "#ff8800" },
    { name = ".gitattributes" ,text = "", fg = "#ff8800" },

# Dotfiles
    { name = ".DS_Store"    ,text = "", fg = "#6d8086"},
    { name = ".bashrc"      ,text = "", fg = "#6d8086"},
    { name = ".bashprofile" ,text = "", fg = "#6d8086"},
    { name = ".zshrc"       ,text = "", fg = "#6d8086"},
    { name = ".zshenv"      ,text = "", fg = "#6d8086"},
    { name = ".zprofile"    ,text = "", fg = "#6d8086"},
    { name = ".vimrc"       ,text = "", fg = "#019833" },
    { name = "*.ps1"        ,text = "󰨊", fg = "#4273ca" },

# Text
    { name = "*.txt"   ,text = "", fg = "#89e051" },
    { name = "*.md"    ,text = "", fg = "#000000" },  # 
    { name = "*.tex"   ,text = "ﭨ", fg = "#46c8a8" },
    { name = "*.org"   ,text = "", fg = "#5dbd7e" },
    { name = "*.norg"  ,text = "", fg = "#5dbd7e" },
    { name = "*.rst"   ,text = "", fg = "#7e60c0" },
    { name = "COPYING" ,text = "", fg = "#cbcb41" },
    { name = "LICENSE" ,text = "", fg = "#cbcb41" },

# Archives
    { name = "*.zip" ,text = "", fg = "#f4b8e4" },
    { name = "*.rar" ,text = "", fg = "#f4b8e4" },
    { name = "*.tar" ,text = "", fg = "#f4b8e4" },
    { name = "*.gz"  ,text = "", fg = "#f4b8e4" },
    { name = "*.7z"  ,text = "", fg = "#f4b8e4" },
    { name = "*.bz2" ,text = "", fg = "#f4b8e4" },
    { name = "*.xz"  ,text = "", fg = "#f4b8e4" },

# Documents
    { name = "*.pdf"  ,text = "", fg = "#b30b00" },
    { name = "*.caj"  ,text = "", fg = "#b30b00" },
    { name = "*.doc"  ,text = "", fg = "#185abd" },
    { name = "*.doct" ,text = "", fg = "#185abd" },
    { name = "*.docx" ,text = "", fg = "#185abd" },
    { name = "*.dot"  ,text = "", fg = "#185abd" },
    { name = "*.pom"  ,text = "", fg = "#cb4a32" },
    { name = "*.pot"  ,text = "", fg = "#cb4a32" },
    { name = "*.ppm"  ,text = "", fg = "#cb4a32" },
    { name = "*.pps"  ,text = "", fg = "#cb4a32" },
    { name = "*.ppt"  ,text = "", fg = "#cb4a32" },
    { name = "*.potx" ,text = "", fg = "#cb4a32" },
    { name = "*.ppmx" ,text = "", fg = "#cb4a32" },
    { name = "*.ppsx" ,text = "", fg = "#cb4a32" },
    { name = "*.pptx" ,text = "", fg = "#cb4a32" },
    { name = "*.xlc"  ,text = "", fg = "#207245" },
    { name = "*.xlm"  ,text = "", fg = "#207245" },
    { name = "*.xls"  ,text = "", fg = "#207245" },
    { name = "*.xlt"  ,text = "", fg = "#207245" },
    { name = "*.xlsm" ,text = "", fg = "#207245" },
    { name = "*.xlsx" ,text = "", fg = "#207245" },
    { name = "*.csv"  ,text = "", fg = "#207245" },
    { name = "*.ods"  ,text = "", fg = "#207245" },
    { name = "*.ots"  ,text = "", fg = "#207245" },

# Audio
    { name = "*.mp3"  ,text = "", fg = "#d39ede" },
    { name = "*.flac" ,text = "", fg = "#d39ede" },
    { name = "*.wav"  ,text = "", fg = "#d39ede" },
    { name = "*.aac"  ,text = "", fg = "#d39ede" },
    { name = "*.ogg"  ,text = "", fg = "#d39ede" },
    { name = "*.m4a"  ,text = "", fg = "#d39ede" },
    { name = "*.mp2"  ,text = "", fg = "#d39ede" },

# Movies
    { name = "*.mp4"  ,text = "", fg = "#9ea3de" },
    { name = "*.mkv"  ,text = "", fg = "#9ea3de"  },
    { name = "*.avi"  ,text = "", fg = "#9ea3de"  },
    { name = "*.mov"  ,text = "", fg = "#9ea3de" },
    { name = "*.webm" ,text = "", fg = "#9ea3de"  },
    { name = "*.rmvb" ,text = "", fg = "#9ea3de"  },

# Images
    { name = "*.jpg"  ,text = "", fg = "#3AFFDB" },  # 
    { name = "*.jpeg" ,text = "", fg = "#3AFFDB" },  # 
    { name = "*.tif"  ,text = "", fg = "#3AFFDB" },  # 
    { name = "*.png"  ,text = "", fg = "#3AFFDB" },  # 
    { name = "*.gif"  ,text = "", fg = "#3AFFDB" },  # 
    { name = "*.emf"  ,text = "", fg = "#3AFFDB" },  # 
    { name = "*.webp" ,text = "", fg = "#3AFFDB" },  # 
    { name = "*.avif" ,text = "", fg = "#3AFFDB" },  # 
    { name = "*.bmp"  ,text = "", fg = "#3AFFDB" },  # 
    { name = "*.ico"  ,text = "", fg = "#3AFFDB" },  # 
    { name = "*.svg"  ,text = "", fg = "#3AFFDB" },  # 
    { name = "*.xcf"  ,text = "", fg = "#3AFFDB" },  # 
    { name = "*.HEIC" ,text = "", fg = "#3AFFDB" },  # 

# Programming
    { name = "*.c"           ,text = "", fg = "#519aba" },
    { name = "*.cpp"         ,text = "", fg = "#519aba" },
    { name = "*.h"           ,text = "", fg = "#a074c4" },
    { name = "*.hpp"         ,text = "", fg = "#a074c4" },
    { name = "*.rs"          ,text = "", fg = "#dea584" },
    { name = "*.go"          ,text = "", fg = "#7FD6E9" },
    { name = "*.py"          ,text = "", fg = "#FFBC03" },
    { name = "*.pyc"         ,text = "", fg = "#ffe291" },
    { name = "*.pyd"         ,text = "", fg = "#ffe291" },
    { name = "*.pyi"         ,text = "", fg = "#ffbc03" },
    { name = "*.pyo"         ,text = "", fg = "#ffe291" },
    { name = "*.pyx"         ,text = "", fg = "#5aa7e4" },
    { name = "*.js"          ,text = "", fg = "#cbcb41" },
    { name = "*.ts"          ,text = "", fg = "#519aba" },
    { name = "*.tsx"         ,text = "", fg = "#519aba" },
    { name = "*.jsx"         ,text = "", fg = "#519aba" },
    { name = "*.rb"          ,text = "", fg = "#701516" },
    { name = "*.php"         ,text = "", fg = "#a074c4" },
    { name = "*.java"        ,text = "", fg = "#cc3e44" },
    { name = "*.sh"          ,text = "", fg = "#4d5a5e" },
    { name = "*.fish"        ,text = "", fg = "#4d5a5e" },
    { name = "*.swift"       ,text = "", fg = "#e37933" },
    { name = "*.vim"         ,text = "", fg = "#019833" },
	{ name = "*.lua"         ,text = "", fg = "#51a0cf" },
    { name = "*.html"        ,text = "", fg = "#e34c26" },
    { name = "*.css"         ,text = "", fg = "#61afef" },
    { name = "*.scss"        ,text = "", fg = "#f55385" },
    { name = "*.json"        ,text = "", fg = "#cbcb41" },
    { name = "*.toml"        ,text = "", fg = "#6d8086" },
    { name = "*.yml"         ,text = "", fg = "#6d8086" },
    { name = "*.yaml"        ,text = "", fg = "#6d8086" },
    { name = "*.ini"         ,text = "", fg = "#6d8086" },
    { name = "*.conf"        ,text = "", fg = "#6d8086" },
    { name = "*.lock"        ,text = "", fg = "#f80000" },
    { name = "*.nix"         ,text = "", fg = "#7ebae4" },
    { name = "*.m"           ,text = "", fg = "#c04c0b" },
    { name = "*.for"         ,text = "", fg = "#bd93f9" },  # 󱈚
    { name = "*.lnk"         ,text = "", fg = "#e3459f" },
    { name = "*.opju"        ,text = "ﴝ", fg = "#f66d54" },
    { name = "*.log"         ,text = "", fg = "#6d8086" },
    { name = "*.DAT"         ,text = "", fg = "#7ebae4" },
    { name = "*.db"          ,text = "", fg = "#6d8086" },
    { name = "*.dll"         ,text = "", fg = "#6d8086" },
    { name = "*.ahk"         ,text = "", fg = "#019833" },
    { name = "*.tmp"         ,text = "", fg = "#ffffff" },
    { name = "*.el"          ,text = "", fg = "#7f5ab6" },
    { name = "*.lib"         ,text = "", fg = "#ffffff" },
    { name = "*.dic"         ,text = "﬜", fg = "#f77a91" },
    { name = "*.ttf"         ,text = "", fg = "#ECECEC" },
    { name = "*.otf"         ,text = "", fg = "#ECECEC" },
    { name = "*.xml"        ,text = "謹", fg = "#e34c26" },
    { name = "Containerfile" ,text = "󰡨", fg = "#384d54" },
    { name = "Dockerfile"    ,text = "󰡨", fg = "#384d54" },

    # CAD
    { name = "*.stp"         ,text = "", fg = "#4273ca" },
    { name = "*.step"        ,text = "", fg = "#4273ca" },
    { name = "*.igs"         ,text = "", fg = "#4273ca" },
    { name = "*.iges"        ,text = "", fg = "#4273ca" },
    { name = "*.x_t"         ,text = "", fg = "#4273ca" },

    # CAE-Abaqus
    { name = "*.cae"         ,text = "", fg = "#11a7a3" },
    { name = "*.inp"         ,text = "", fg = "#11a7a3" },
    { name = "*.rpy"         ,text = "", fg = "#ffe291" },
    { name = "*.odb"         ,text = "", fg = "#11a7a3" },
    { name = "*.com"         ,text = "", fg = "#11a7a3" },
    { name = "*.prt"         ,text = "", fg = "#11a7a3" },
    { name = "*.msg"         ,text = "", fg = "#11a7a3" },  # 

    # CAE-Hypermesh
    { name = "*.hm"          ,text = "ﴧ", fg = "#fa4616" },
    { name = "*.cfg"         ,text = "", fg = "#6d8086" },

# Misc
    { name = "*.bin" ,text = "", fg = "#05a6f0" },
    { name = "*.exe" ,text = "", fg = "#00fa9a" },
    # { name = "*.exe" ,text = "", fg = "#9F0500" },
    { name = "*.pkg" ,text = "", fg = "#10bb10" },
    { name = "*.bat" ,text = "", fg = "#C1F12E" },

# Default
    { name = "*"  ,text = "" }, # files icon   
    { name = "*/" ,text = "" }, # directories icon  
]

# : }}}
