# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#8ae234" }

# Hovered
hovered         = { fg = "#ab7ca5", bg = "#450e34" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#cc0000", bold = true }
find_position = { fg = "magenta", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "lightgreen",  bg = "lightgreen" }
marker_copied   = { fg = "lightyellow", bg = "lightyellow" }
marker_cut      = { fg = "lightred",    bg = "lightred" }

# Tab
tab_active   = { fg = "#2e3436", bg = "#450e34" }
tab_inactive = { fg = "#abb2bf", bg = "darkgray" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#626880" }

# Offset
folder_offset  = [ 1, 0, 1, 0 ]
preview_offset = [ 1, 1, 1, 1 ]

# Highlighting
syntect_theme = ""

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "darkgray", bg = "darkgray" }

# Mode
mode_normal = { fg = "#2e3436", bg = "#89a0c3", bold = true }
mode_select = { fg = "#2e3436", bg = "lightgreen", bold = true }
mode_unset  = { fg = "#2e3436", bg = "lightmagenta", bold = true }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#89a0c3", bg = "#2e3436" }
progress_error  = { fg = "red", bg = "#2e3436" }

# Permissions
permissions_t = { fg = "lightgreen" }
permissions_r = { fg = "lightyellow" }
permissions_w = { fg = "lightred" }
permissions_x = { fg = "lightcyan" }
permissions_s = { fg = "darkgray" }

# : }}}


# : Select {{{

[select]
border   = { fg = "blue" }
active   = { fg = "magenta" }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#ab7ca5" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border   = { fg = "blue" }
active   = { bg = "darkgray" }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "blue" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#300a24" }
cand            = { fg = "#c4a000" }
rest            = { fg = "darkgray" }
desc            = { fg = "#ad7fa8" }
separator       = "  "
separator_style = { fg = "darkgray" }

# : }}}


# : Help {{{

[help]
on      = { fg = "magenta" }
exec    = { fg = "cyan" }
desc    = { fg = "gray" }
hovered = { bg = "darkgray", bold = true }
footer  = { fg = "#2e3436", bg = "#abb2bf" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "cyan" },

	# Videos
	{ mime = "video/*", fg = "yellow" },
	{ mime = "audio/*", fg = "yellow" },

	# Archives
	{ mime = "application/zip",             fg = "magenta" },
	{ mime = "application/gzip",            fg = "magenta" },
	{ mime = "application/x-tar",           fg = "magenta" },
	{ mime = "application/x-bzip",          fg = "magenta" },
	{ mime = "application/x-bzip2",         fg = "magenta" },
	{ mime = "application/x-7z-compressed", fg = "magenta" },
	{ mime = "application/x-rar",           fg = "magenta" },
	{ mime = "application/xz",              fg = "magenta" },

	# Documents
	{ mime = "application/doc",   fg = "green" },
	{ mime = "application/pdf",   fg = "green" },
	{ mime = "application/rtf",   fg = "green" },
	{ mime = "application/vnd.*", fg = "green" },

	# Fallback
	{ name = "*", fg = "#abb2bf" },
	{ name = "*/", fg = "#876fab" }
]

[icons]

"Desktop/"     = ""
"Documents/"   = ""
"Downloads/"   = ""
"Pictures/"    = ""
"Music/"       = ""
"Movies/"      = ""
"Videos/"      = ""
"Public/"      = ""
"Library/"     = ""
"Development/" = ""
".config/"     = ""

# Git
".git/"          = ""
".gitignore"     = ""
".gitmodules"    = ""
".gitattributes" = ""

# Dotfiles
".DS_Store"    = ""
".bashrc"      = ""
".bashprofile" = ""
".zshrc"       = ""
".zshenv"      = ""
".zprofile"    = ""
".vimrc"       = ""

# Text
"*.txt" = ""
"*.md"  = ""
"*.rst" = ""
COPYING = "󰿃"
LICENSE = "󰿃"

# Archives
"*.zip" = ""
"*.tar" = ""
"*.gz"  = ""
"*.7z"  = ""
"*.bz2" = ""
"*.xz"  = ""

# Documents
"*.csv"  = ""
"*.doc"  = ""
"*.doct" = ""
"*.docx" = ""
"*.dot"  = ""
"*.ods"  = ""
"*.ots"  = ""
"*.pdf"  = ""
"*.pom"  = ""
"*.pot"  = ""
"*.ppm"  = ""
"*.pps"  = ""
"*.ppt"  = ""
"*.potx" = ""
"*.ppmx" = ""
"*.ppsx" = ""
"*.pptx" = ""
"*.xlc"  = ""
"*.xlm"  = ""
"*.xls"  = ""
"*.xlt"  = ""
"*.xlsm" = ""
"*.xlsx" = ""

# Audio
"*.mp3"  = ""
"*.flac" = ""
"*.wav"  = ""
"*.aac"  = ""
"*.ogg"  = ""
"*.m4a"  = ""
"*.mp2"  = ""

# Movies
"*.mp4"  = ""
"*.mkv"  = ""
"*.avi"  = ""
"*.mov"  = ""
"*.webm" = ""

# Images
"*.jpg"  = ""
"*.jpeg" = ""
"*.png"  = ""
"*.gif"  = ""
"*.webp" = ""
"*.avif" = ""
"*.bmp"  = ""
"*.ico"  = ""
"*.svg"  = ""
"*.xcf"  = ""
"*.HEIC" = ""

# Programming
"*.c"         = ""
"*.cpp"       = ""
"*.h"         = ""
"*.hpp"       = ""
"*.rs"        = ""
"*.go"        = ""
"*.py"        = ""
"*.js"        = ""
"*.ts"        = ""
"*.tsx"       = ""
"*.jsx"       = ""
"*.rb"        = ""
"*.php"       = ""
"*.java"      = ""
"*.sh"        = ""
"*.fish"      = ""
"*.swift"     = ""
"*.vim"       = ""
"*.lua"       = ""
"*.html"      = ""
"*.css"       = ""
"*.scss"      = ""
"*.json"      = ""
"*.toml"      = ""
"*.yml"       = ""
"*.yaml"      = ""
"*.ini"       = ""
"*.conf"      = ""
"*.lock"      = ""
"*.nix"       = ""
Containerfile = "󰡨"
Dockerfile    = "󰡨"

# Misc
"*.bin" = ""
"*.exe" = ""
"*.pkg" = ""

# Default
"*"  = ""
"*/" = ""

# : }}}
