[manager]
ratio         = [ 1, 4, 3 ]
sort_by        = "modified"
sort_sensitive = true
sort_reverse   = true
sort_dir_first = false
linemode       = "none"
show_hidden    = false
show_symlink   = true
scrolloff      = 5
mouse_events = []


[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15


[opener]
nvim = [
	{ run = 'nvim "%*"',    block = true, desc = "Neovim", for = "windows" },
]
open = [
	{ run = 'start "" "%1"', orphan = true, desc = "Open by default", for = "windows" },
]
extract = [
    { run = 'ouch d -y "%*"', desc = "Extract here with ouch", for = "windows" },
]
play = [
	{ run = 'mpv "%1"', orphan = true, desc = "MPV", for = "windows" },
]


[open]
rules = [
	{ name = "*/", use = [ "open" ] },

	{ mime = "text/*",  use = [ "nvim", "open" ] },
	{ mime = "image/*", use = [ "open" ] },
	{ mime = "video/*", use = [ "play" ] },
	{ mime = "audio/*", use = [ "play" ] },
	{ mime = "inode/x-empty", use = [ "nvim", "open" ] },

	{ mime = "application/json", use = [ "nvim", "open" ] },
	{ mime = "*/javascript",     use = [ "nvim", "open" ] },

	{ mime = "application/zip",             use = [ "open", "extract" ] },
	{ mime = "application/gzip",            use = [ "open", "extract" ] },
	{ mime = "application/x-tar",           use = [ "open", "extract" ] },
	{ mime = "application/x-bzip",          use = [ "open", "extract" ] },
	{ mime = "application/x-bzip2",         use = [ "open", "extract" ] },
	{ mime = "application/x-7z-compressed", use = [ "open", "extract" ] },
	{ mime = "application/x-rar",           use = [ "open", "extract" ] },
    { mime = "application/xz",              use = [ "open", "extract" ] },

	{ mime = "*", use = [ "nvim", "open" ] },
]


[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
image_alloc      = 536870912  # 512MB
image_bound      = [ 0, 0 ]
suppress_preload = false


[plugin]

fetchers = [
	{ id = "mime-ext", name = "*", run = "mime-ext",if = "!mime", prio = "high" },
]

prepend_previewers = [
# plugin:glow.yazi
  { name = "*.md", run = "glow" },

# plugin:ouch.yazi
  { mime = "application/*zip",            run = "ouch" },
  { mime = "application/x-tar",           run = "ouch" },
  { mime = "application/x-bzip2",         run = "ouch" },
  { mime = "application/x-7z-compressed", run = "ouch" },
  { mime = "application/x-rar",           run = "ouch" },
  { mime = "application/x-xz",            run = "ouch" },
]


